#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Updates the docker containers for this project.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    echo "==Building image..."
    docker-compose build

fi
